add pkgConfig
moretea/yarn2nix pull request #14
Opened 2017-03-13 14:00 UTC by manveru

Will add a better description later, this is just a quick and dirty first implementation.

2017-03-13 14:52 UTC, manveru commented
Example usage:

```
{nixpkgs, nodejs}: rec {
  pkgs = import nixpkgs {};
  base = (import (
    fetchTarball https://github.com/manveru/yarn2nix/archive/ca4ebb1029bea25d8ef558754f4a6af06d9b8e33.tar.gz
  ) {
    inherit pkgs nodejs;
  });
  yarnPackages = base.buildYarnPackage rec {
    name = "eqipia-yarn-packages";
    publishBinsFor = [
      "webpack"
      "jest"
      "modernizr"
      "prettier-eslint-cli"
    ];

    nodeHeaders = pkgs.fetchurl {
      url = "https://nodejs.org/download/release/v${nodejs.version}/node-v${nodejs.version}-headers.tar.gz";
      sha256 = "01cq2lszd3lmgy2pshfji5117inr0j8vdqxv3cps551s9qyigik5";
    };

    pkgConfig = {
      node-sass = {
        buildInputs = [ pkgs.libsass pkgs.python ];
        postInstall = ''
          node scripts/build.js --tarball=${nodeHeaders}
        '';
      };
    };

    filtered = builtins.filterSource (
      path: type: ( toString ../package.json ) == path
    ) ../.;
    src = (builtins.trace filtered filtered);

    packageJson = ../package.json;
    yarnLock = ../yarn.lock;
    yarnNix = ../yarn.nix;
  };
  yarn = pkgs.yarn;
  yarn2nix = base.yarn2nix;
}
```

2017-03-13 16:40 UTC, manveru commented
@zimbatm @moretea can you try this maybe? It's working pretty well here, but we can maybe add a shared pkgConfig over time.

Either way this is performing much better now than node2nix. The biggest issue I still have is that in the above example, `node-sass` will be rebuilt every time the `packages.json` changes. Maybe there's a better way around that too.

2017-03-14 01:13 UTC, moretea commented
Ah yes, the nomenclature for this is 'overrides'. That's how they're called in `bundix` and `pipy2nix`

2017-03-14 09:39 UTC, zimbatm commented on default.nix
> +        yarn config --offline set yarn-offline-mirror ${offlineCache}
what difference does that do?

2017-03-14 09:41 UTC, manveru commented on default.nix
> +        yarn config --offline set yarn-offline-mirror ${offlineCache}
It won't output a warning, mostly cosmetic.

2017-03-14 09:42 UTC, manveru commented
Almost done adding `patchShebangs` for the executables, so they can also be run without `/usr/bin/env` or `nodejs` in the PATH

2017-03-14 09:43 UTC, zimbatm reviewed
LGTM overall.

I'm not convinced about the `pkgConfig` naming but can live with it.

I'm not convinced that it's the right way of overriding the packages. If they were derivations then I would suggest a fix-point but they are not.

2017-03-14 09:44 UTC, zimbatm commented on default.nix
> +        sed -i -E 's|^(\s*resolved\s*")https?://.*/|\1|' yarn.lock
Dou you remember what problem that sed change solved?

2017-03-14 09:44 UTC, manveru commented
Yeah, I'd really love to make each package a separate derivation, but that's not feasable right now. Maybe if we parse the `package.json` and generate a `yarn.lock` for each, but that'd probably result in conflicts.

2017-03-14 09:45 UTC, zimbatm commented on default.nix
> +      buildInputs = [ yarn nodejs ] ++ moreBuildInputs;
I'm not sure what would happen if a buildInput was duplicated

2017-03-14 09:46 UTC, manveru commented on default.nix
> +        sed -i -E 's|^(\s*resolved\s*")https?://.*/|\1|' yarn.lock
We're using a private npm registry, the lines look like this:
`  resolved "http://10.11.22.33:8080/a/accepts/_attachments/accepts-1.3.3.tgz#c3ca7434938648c3e0d9c1e328dd68b622c284ca"`, this regex handles both private and public.

2017-03-14 09:47 UTC, manveru commented on default.nix
> +      buildInputs = [ yarn nodejs ] ++ moreBuildInputs;
Do you know a way to uniq them? There's also the issue of sorting, but I think this might work for 99% of cases?

2017-03-14 09:51 UTC, zimbatm commented on default.nix
> +      buildInputs = [ yarn nodejs ] ++ moreBuildInputs;
I don't know how to do it without forcing their evaluation. I'm happy if we keep that in mind and solve it only if it becomes a problem.

2017-03-14 09:53 UTC, manveru commented
Well, I just confirmed that I can now build our production docker image using yarn2nix, so for now I'm done with this PR (that was my goal for it anyway). :tada:

2017-03-14 10:03 UTC, zimbatm approved these changes

2017-03-14 20:29 UTC, moretea requested changes
Great!

2017-03-14 20:29 UTC, moretea commented on default.nix
> +      moreBuildInputs = (pkgs.lib.flatten (builtins.map (key:
`moreBuildInputs` -> `extraBuildInputs`

2017-03-14 20:29 UTC, moretea commented on default.nix
> +{ pkgs ? (import <nixpkgs> {}), nodejs ? pkgs.nodejs-7_x}:
Does this `pkgs` refer to the `pkgs` in the same line? Otherwise we could pass in the attribute path (`["nodejs-7x"]` in this case)

2017-03-14 20:29 UTC, moretea commented on default.nix
> +        if (pkgConfig.${key} ? "postInstall") then
No need to have postInstall in quotes here btw :)

```
nix-repl> { a = true; } ? a
true
```

2017-03-14 20:29 UTC, moretea commented on default.nix
> +            test -e node_modules/${key} && (
So this would not work for nested js dependencies, right? Only the top level ones.

Is there a special reason that you're adding this test in here? I think that I would prefer it to fail badly if you'd include a wrong override.

2017-03-14 20:29 UTC, moretea commented on default.nix
> +      buildInputs = [ yarn nodejs ] ++ moreBuildInputs;
The sorting will be in the order that you'd add the things to the list. Only the order of attrsets is guarranteed to be alphabetical w.r.t the keys.

I would not worry (yet) about a problem there.

2017-03-14 22:10 UTC, manveru commented on default.nix
> +{ pkgs ? (import <nixpkgs> {}), nodejs ? pkgs.nodejs-7_x}:
yes, it is the same `pkgs`.

2017-03-14 22:11 UTC, manveru commented on default.nix
> +        if (pkgConfig.${key} ? "postInstall") then
ah, i translated it from `hasAttr`, but the syntax form doesn't need them indeed.

2017-03-14 22:21 UTC, manveru commented on default.nix
> +            test -e node_modules/${key} && (
That's mostly so you can add some common configuration in `buildYarnPackage` that can be used as a default by everybody, and they just add special cases they need. It's similar to how `bundlerEnv` works, just that we can't do it on a per-derivation basis but have to rely on directory names.
In theory we could use something like this:

    for f in $(find -L -path '*/node_modules/${key}' -type d); do
      (cd "$f" && (${pkgConfig.${key}.postInstall}))
    done

2017-03-15 12:33 UTC, manveru commented
Looks like this still is broken for `node-sass` on darwin, I'll investigate that failure in a bit, but it might mean we need to make `pkgConfig` platform dependent.

2017-03-16 08:43 UTC, manveru commented
@moretea anything else needed to do here?

2017-03-21 23:18 UTC, moretea approved these changes

2017-03-21 23:18 UTC, moretea commented on default.nix
> +            test -e node_modules/${key} && (
LGTM!

As I said on IRC:
> The problem with that is that it cannot take namespace collisions into account. In theory we could parse the requirements.json and check for e.g. homepage. For the first version this is more than sufficient.

2017-03-21 23:18 UTC, moretea commented on default.nix
> +{ pkgs ? (import <nixpkgs> {}), nodejs ? pkgs.nodejs-7_x}:
OK cool!

2017-03-21 23:19 UTC, merged